- Guias/GuiaDelAO.md
Solo agregando la guía de Architecture Owner :)
> Documento de guia de AO

- docs/Guias/GuiaDelPM.md
Se agregó la descripción y las responsabilidades de un Program Manager.
> Documento de guía de PM

- docs/Guias/CreacionDeProceso.md
- docs/Plantillas/Proceso.md
- docs/Procesos/Proceso.md
En este pull request está la propuesta para crear nuevos procesos departamentales. Incluye los siguientes elementos:
1. Proceso para crear nuevos procesos
2. Guía de los elementos de un proceso
3. Plantilla para creación de nuevo proceso
> Proceso y guía para la creación de nuevos procesos departamentales

- docs/Procesos/Junta.md
Se modificó el proceso de junta para seguir la nueva plantilla propuesta en el proceso para creación de nuevos procesos.
1. Se agregó la versión del proceso.
2. Se agregaron los autores del proceso.
3. Se modificó la plantilla utilizada.
> Mejora del proceso de junta

- docs/Arquitectura/Casa Mosaico/ArqCasaMosaico_resumen.md
- docs/Arquitectura/Casa Mosaico/NecesidadesBackend.md
Se actualizó el documento de arquitectura del proyecto de casa mosaico después de haber evaluado y tomado decisiones con el equipo.
> Update arquitectura casa mosaico

- docs/Guias/guiaPP.md
Guia de Project Planning agregada.
> Guia agregada

- docs/Procesos/Queja.md
- docs/codigoEtica.md
- Agregar los valores correctos.
> Valores del código de ética

- docs/Arquitectura/Casa Mosaico/NecesidadesBackend.md
Se agregó al MD la tabla que se tenía en el sheets en el drive. No hay ningún cambio de components o datos.
> agregar tabla necesidades backend

- docs/Guias/GuiaDefinicionAssets.md
Se creo la guía para la definición de Assets
> Docs/Guías/Definición Assets

- docs/Procesos/Definicion de plan.md
- docs/Procesos/DefinicionDeObjetivosDeProyecto.md
- docs/Procesos/DefinirUserStories.md
- Agregar el id de los procesos en el título
- Corregir pequeños errores de puntuación
- Seguir la plantilla actual de proceso
> Seguir estándar de nombramiento de procesos

- docs/Guias/GuiaMatrizDeRiesgos.md
- docs/Plantillas/MatrizDeRiesgos.md
- docs/Procesos/GestiónDeRiesgos.md
De parte de RSKM, se dejan disponibles dos procesos y una guia del area de gestion de riesgos.
> Add processes and template

- docs/Politicas/PO01.md
- docs/Politicas/PO02.md
- docs/Politicas/PO03.md
> feat(politicas): 📝 politicas-cm

- docs/Definiciones/DefinicionREQM.md
Añadir control de versiones a documentacion de REQM
> fix(requirement management): :memo: 

- docs/Procesos/PR01.md
- docs/Procesos/PR04.md
- docs/Procesos/PR07.md
- docs/Procesos/PR08.md
- docs/Procesos/PR09.md
- docs/Procesos/PR10.md
- docs/Procesos/PR11.md
- docs/Procesos/PR13.md
- docs/Procesos/PR14.md
- docs/Procesos/PR17.md
Corrección ortográfica y de sintaxis de los procesos actuales del departamento.
> fix(docs): corregir ortografía y redacción de procesos

- docs/Definiciones/DE01.md
- docs/Definiciones/DE02.md
- docs/Definiciones/DE03.md
- docs/Politicas/PO01.md
- docs/Politicas/PO02.md
- docs/Politicas/PO03.md
- docs/Politicas/PO04.md
Corrección de ortografía y de la redacción de las políticas y definiciones actuales.
> fix(docs): corregir ortografía y redacción de políticas y definiciones

- docs/Guias/GU01.md
- docs/Guias/GU02.md
- docs/Guias/GU03.md
- docs/Guias/GU04.md
- docs/Guias/GU05.md
- docs/Guias/GU06.md
- docs/Guias/GU07.md
- docs/Guias/GU08.md
- docs/Guias/GU09.md
- docs/Guias/GU10.md
- docs/Guias/GU11.md
- docs/Guias/GU12.md
- docs/Guias/GU13.md
- docs/Guias/GU14.md
- docs/Guias/GU15.md
- docs/Guias/GU16.md
Corrección ortográfica y de sintaxis de las guías actuales del departamento.
> fix(docs): corregir ortografía y redacción de guías

- docs/Plantillas/PL01.md
- docs/Plantillas/PL02.md
- docs/Plantillas/PL03.md
- docs/Plantillas/PL04.md
- docs/Plantillas/PL05.md
- docs/Plantillas/PL06.md
- docs/Plantillas/PL07.md
- docs/Plantillas/PL08.md
- docs/Plantillas/PL09.md
- docs/Plantillas/PL10.md
Correcciones de ortografía y sintaxis de las plantillas actuales del departamento.
> fix(docs): corregir ortografía y redacción de plantillas

- docs/Plantillas/PL12.md
- docs/Procesos/PR01.md
Se añadió la plantilla de PPQA
> docs(PPQA): :memo: Plantilla PPQA

- docs/Guias/GU12.md
Se agregó la mención de la plantilla de la bitácora y se arreglaron discrepancias que causaban inconsistencias en la documentación.
> Update 1.3 GU12

- docs/Definiciones/DE11.md
> docs: creacion de definicion

- docs/Procesos/PR22.md
Proceso que hemos estado realizando para hacer el reporte de Estado, pero ya institucionalizado!
Para propósitos de PMC.
> docs(PMC): Añadir Proceso de Reporte de Estado

- docs/Politicas/PO04.md
Se creo una política de validación de proyecto
> feat(policy):📝 Create project validation policy

- docs/Procesos/PR15.md
Proceso que ya realizamos, institucionalizado por PMC!
> docs: Añadir PR15, Proceso de 1 o 1s para PMs y TLs

- docs/Guias/GU19.md
- docs/Procesos/PR06.md
Arreglar el formato de GU19 y agregar el enlace de la guía al PR06.
> Corrección de formato de la guía

- docs/Procesos/PR09.md
> fix(Procesos): :memo: Institucionalización

- .github/workflows/ci.yml
- docs/Guias/GU13.md
- package-lock.json
Últimos ajustes a la GU13. Proporciona una plantilla y demás
> Ajustes finales GU13

- docs/Procesos/PR19.md
Se fregaron SP de PP dentro del proceso de coordinación de juntas diarias.
> Agregar subprácticas de PP y actualizar versionado

- docs/Guias/GU19.md
Agregar a guia de planes la definición de ciclos de vida de proyectos.
> Agregar ciclos de vida de proyectos.

- docs/Procesos/PR01.md
> feat: :sparkles: ppqa lessons learned

- docs/Guias/GU20.md
La Guía que te debía @AlbertoMatuteB !
> docs: Add GU20

- docs/Procesos/PR30.md
Creación de PR30-Identificación de fracaso de un plan y mitigación del mismo
> feat: ✨Creación de PR30
